DROP TABLE users IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar,
	login varchar,
	email varchar,
	birthday timestamp
);

DROP TABLE films IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS films (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date timestamp,
    duration int,
    rate int,
    mpa int
);

DROP TABLE genres IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS genres(
    genre_id int PRIMARY KEY,
    genre_name varchar
);

DROP TABLE friends IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users(id),
    friend_id int REFERENCES users(id),
    PRIMARY KEY (user_id, friend_id)
);

DROP TABLE likes IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films(id),
    user_id int REFERENCES users(id),
    PRIMARY KEY (film_id, user_id)
);

DROP TABLE films_genre IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS films_genre(
    film_id int REFERENCES films(id),
	genre_id int REFERENCES genres(genre_id),
	PRIMARY KEY (film_id, genre_id)
);

DROP TABLE mpa_rating IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS mpa_rating(
    mpa_id int PRIMARY KEY,
    mpa_name varchar
);
